### ISSUE TITLE
ConfigMap and Secret are not deleted when Database is deleted

### ISSUE THREAD

**Issue by imgrant** [kloeckner-i/db-operator#163]
Hello! After endless googling for K8s MySQL operators, I think this is the one for me!
I tested it out, and was able to successfully create a database (schema), and then delete it. However, after deleting, I am still left with the database ConfigMap and Secret that the operator created for the database that it created (and then deleted) — is this by design? I had expected it to clean up completely, since it removed the database and user from the database server.

**Comment by imgrant** [comment]
Ah I see, thanks. Great to hear it's on the roadmap. In my case I plan to use it for ephemeral dev environments, so without cleanup those ConfigMaps and Secrets would accumulate with every new PR.

**Comment by hyunysmile** [comment]
Totally understand and make sense proper cleaning in your usecase.
I will try to do this ticket in next sprint.

**Comment by allanger** [comment]
@imgrant 
Now, if you want to remove secrets, configmaps, backup cronjobs and proxy deployments, that were deployed by db-operator after creating a `database` resource, you can use the `cleanup` field. So your database manifest looks like:
```
apiVersion: "kci.rocks/v1alpha1"
kind: "Database"
metadata:
  name: "example-db"
spec:
  ...
  cleanup: true
  ...
```
If it's set to `true`, db-operator will add owner references to those resources and when a database is gone, everything else will follow in its footsteps.

**Comment by imgrant** [comment]
@allanger Thanks! Just got round to testing this out. I added `cleanup: true`, and it does delete the `ConfigMap`, but not the `Secret` (I am not using backup cron jobs or proxies). I get the following error:

```
level=error msg="failed to update status - Operation cannot be fulfilled on databases.kci.rocks \"example-db\": StorageError: invalid object, Code: 4, Key: /registry/kci.rocks/databases/default/example-db, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: d780cdf3-1283-4470-a573-35dbd73252ee, UID in object meta: "
```

**Comment by allanger** [comment]
Hi, @imgrant 
I've checked the connection string creation function, and I think I've made a typo there, so removing is not working, yes. 

But since the `connectionStringTemplate` is going to be removed soon, I'm not sure if it makes sense to fix it. (I'm already working on upgrading the CRD version, and `connectinonString` is not going to be presented anymore). So I hope you're fine with using `secretsTemplates` instead of it. 

The error you've sent, as far as I know, is old, and it's not related to this issue. But it's not critical and only exists in logs, as I remember, so getting rid of it is not a high priority now.
