### ISSUE TITLE
v0.6.3

### ISSUE THREAD

**Issue by paulrostorp** [kloeckner-i/db-operator#78]
I think there is something wrong with the helm chart v0.6.3,  it tries to pull the cloudish-sql image...
The helm chart code on github doesn't seem to match the generated resources

**Comment by frizzr** [comment]
So I think he may be in the middle of an update. cloudish-sql: v1.0.0 is indeed available via Github packages, but 0.13.1 is not....and the missing 'v' is important it seems since Github packages requires the 'v'.

To get around this for now, this version number can be overridden [according to this line](https://github.com/kloeckner-i/db-operator/blob/4a359259f68554818aa6772447bd93a4002ae5c6/helm/db-operator/templates/_helpers.tpl#L38) by specifying

`--set image.tag=v1.0.0`

in the helm install command.

**Comment by frizzr** [comment]
I went ahead and [made a PR](https://github.com/kloeckner-i/db-operator/pull/79) for fixing this.

**Comment by dpeckett** [comment]
Thanks for bringing this to our attention and for the PR! Looks like we published a broken chart that included erroneous references to some of our internal test images. We've published a new release of the db-operator chart (0.6.4) and yanked the old broken release. Let us know if you continue to experience issues.
